/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.gradle.api.Plugin
import org.gradle.api.Project

/** A simple 'hello world' plugin. */
class BuildSrcPlugin : Plugin<Project> {
  override fun apply(project: Project) {
    // Register a task
  }
}
